### ISSUE TITLE
Using the provided materials create InformationForBL device class based on the facadedevice library.

### ISSUE THREAD

**Issue by wkitka** [synchrotron-solaris/dev-solaris-informationforbl#1]
Attributes:
- [x] GeneralInfo
- [x] FillingPattern

Proxy attributes:
- [x] InjectionStatus
- [x] ExperimentEnable
- [x] BeamCurrent_A
- [x] BIMState
- [x] MPSState

Logical attributes:
- [x] OperationStatus
- [x] BeamCurrent_mA

**Comment by LJBD** [comment]
Note: InformationForBL is based on an older version of `facadedevice`. You should check if it's compatible with the newest version and refactor the code if there are things that can be done better with the newest version.
